### ISSUE TITLE
Problem with 'backup' parameter

### ISSUE THREAD

**Issue by x4FF3** [melmorabity/ansible-ftp#3]
Hi, 

when i try to use your module, ill get 

KeyError: 'backup'

```python
The full traceback is:
Traceback (most recent call last):
  File "/home/random/.ansible/tmp/ansible-tmp-1601392183.2-8280-274907447958570/AnsiballZ_ftp.py", line 102, in <module>
    _ansiballz_main()
  File "/home/random/.ansible/tmp/ansible-tmp-1601392183.2-8280-274907447958570/AnsiballZ_ftp.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/random/.ansible/tmp/ansible-tmp-1601392183.2-8280-274907447958570/AnsiballZ_ftp.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.ftp', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ftp_payload_jgpafi95/ansible_ftp_payload.zip/ansible/modules/ftp.py", line 563, in <module>
  File "/tmp/ansible_ftp_payload_jgpafi95/ansible_ftp_payload.zip/ansible/modules/ftp.py", line 552, in main
  File "/tmp/ansible_ftp_payload_jgpafi95/ansible_ftp_payload.zip/ansible/modules/ftp.py", line 355, in _ftp_upload
KeyError: 'backup'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/random/.ansible/tmp/ansible-tmp-1601392183.2-8280-274907447958570/AnsiballZ_ftp.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/david/.ansible/tmp/ansible-tmp-1601392183.2-8280-274907447958570/AnsiballZ_ftp.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/david/.ansible/tmp/ansible-tmp-1601392183.2-8280-274907447958570/AnsiballZ_ftp.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.ftp', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 206, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ftp_payload_jgpafi95/ansible_ftp_payload.zip/ansible/modules/ftp.py\", line 563, in <module>\n  File \"/tmp/ansible_ftp_payload_jgpafi95/ansible_ftp_payload.zip/ansible/modules/ftp.py\", line 552, in main\n  File \"/tmp/ansible_ftp_payload_jgpafi95/ansible_ftp_payload.zip/ansible/modules/ftp.py\", line 355, in _ftp_upload\nKeyError: 'backup'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```

**Comment by melmorabity** [comment]
I've just made some fixes, could you try the latest snapshot?

**Comment by x4FF3** [comment]
hi,

and thanks.
yes i will try it and let you know :)
